import React, { useEffect, useState } from 'react';
import { Building2, Home, RefreshCw, ShieldCheck } from 'lucide-react';
import { reliefApi } from '../backend/reliefApi';
import { OfflineBeneficiaryRecord } from '../engine/offlineDb';
import { AuthUser } from '../store/authStore';

export const OrganizationDashboard: React.FC<{ user: AuthUser; onBackToHome: () => void }> = ({ user, onBackToHome }) => {
  const [records, setRecords] = useState<OfflineBeneficiaryRecord[]>([]);
  const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); const all = await reliefApi.getAdminBeneficiaries(); setRecords(all.filter(record => record.organizationId === user.organizationId)); setLoading(false); };
  useEffect(() => { load(); }, [user.organizationId]);

  return <main className="min-h-screen bg-[#FAF8F5] px-4 py-8 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl space-y-6"><div className="flex flex-col gap-4 border-b border-stone-200 pb-6 sm:flex-row sm:items-end sm:justify-between"><div><button onClick={onBackToHome} className="mb-3 text-xs font-semibold text-[#0F3A5D] hover:underline">Back to public portal</button><p className="text-[11px] font-bold uppercase tracking-[0.18em] text-emerald-700">Organization dashboard</p><h1 className="mt-1 text-3xl font-serif font-bold text-[#0F3A5D]">{user.organizationName}</h1><p className="mt-2 text-sm text-stone-600">Sirf aapki organization ke assigned area records show ho rahe hain.</p></div><button onClick={load} className="inline-flex items-center gap-2 rounded-xl bg-[#0F3A5D] px-4 py-2.5 text-xs font-bold text-white"><RefreshCw className={`h-4 w-4 ${loading ? 'animate-spin' : ''}`} /> Refresh</button></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3"><Metric icon={Home} label="Assigned households" value={records.length} /><Metric icon={ShieldCheck} label="Verified" value={records.filter(record => record.verificationStatus === 'verified').length} /><Metric icon={Building2} label="Active teams" value={new Set(records.map(record => record.teamId)).size} /></div><div className="overflow-x-auto rounded-2xl border border-stone-200 bg-white shadow-sm"><table className="min-w-full text-left text-xs"><thead className="bg-stone-100 text-[10px] uppercase tracking-wider text-stone-500"><tr><th className="px-4 py-3">Household</th><th className="px-4 py-3">Area</th><th className="px-4 py-3">Team</th><th className="px-4 py-3">Aid</th><th className="px-4 py-3">Verification</th></tr></thead><tbody className="divide-y divide-stone-100">{records.map(record => <tr key={record.recordId}><td className="px-4 py-4"><b>{record.applicantName}</b><p className="mt-1 text-stone-500">{record.gothVillage}</p></td><td className="px-4 py-4">{record.areaId}</td><td className="px-4 py-4">{record.teamId}</td><td className="px-4 py-4">{record.aidPackageAllocated}</td><td className="px-4 py-4 font-semibold">{record.verificationStatus}</td></tr>)}{records.length === 0 && <tr><td colSpan={5} className="px-4 py-12 text-center text-stone-500">Is organization ke liye koi record nahi mila.</td></tr>}</tbody></table></div></div></main>;
};

const Metric: React.FC<{ icon: React.ElementType; label: string; value: number }> = ({ icon: Icon, label, value }) => <div className="rounded-xl border border-stone-200 bg-white p-4"><Icon className="h-4 w-4 text-[#0F3A5D]" /><p className="mt-3 text-xl font-bold">{value}</p><p className="text-[11px] text-stone-500">{label}</p></div>;